obstacle_range: 4
raytrace_range: 4.5
footprint: [[-0.3,-0.23],[-0.3,0.23], [0.3, 0.23], [0.3,-0.23]]
#robot_radius: ir_of_robot

observation_sources: scan
scan: {sensor_frame: laser,  observation_persistence: 0.0, max_obstacle_height: 0.4, min_obstacle_height: 0.0, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

